# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3018cfd386eea6aaa91373714487619e"
name = "new-app"
application_url = "https://hat-table-chemicals-lincoln.trycloudflare.com"
embedded = true
handle = "new-app-1034"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_products,read_themes,write_products,write_product_listings,read_product_listings"

[auth]
redirect_urls = ["https://hat-table-chemicals-lincoln.trycloudflare.com/auth/callback", "https://hat-table-chemicals-lincoln.trycloudflare.com/auth/shopify/callback", "https://hat-table-chemicals-lincoln.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
